version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web.dockerfile
    container_name: nginx_raw
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/testraw.test:delegated
    depends_on:
      - php
      - mysql

  mysql:
    image: mysql:5.7.29
    container_name: mysql_raw
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: testraw
      MYSQL_USER: dev
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  php:
    build:
      context: .
      dockerfile: ./docker/php.dockerfile
    container_name: php_raw
    volumes:
      - ./src:/var/www/testraw.test:delegated

  composer:
    build:
      context: .
      dockerfile: ./docker/composer.dockerfile
    container_name: composer_raw
    volumes:
      - ./src:/var/www/testraw.test
    working_dir: /var/www/testraw.test
    depends_on:
      - php
    user: laravel
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
